App/AutoFP.Gerencia.MVC.UI/Controllers/AutenticacaoController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using AutoFP.Gerencia.Infra.CrossCutting.Security.Interface.Service;
using AutoFP.Gerencia.MVC.UI.Controllers.Base;
using AutoFP.Gerencia.MVC.UI.ViewModel;

namespace AutoFP.Gerencia.MVC.UI.Controllers
{
    [AllowAnonymous]
    public class AutenticacaoController : BaseController
    {
        private readonly IUsuarioService _usuarioService;

        public AutenticacaoController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var usuario = _usuarioService.Authenticate(vm.Usuario, vm.Senha);

                    if (!usuario.IsValid)
                    {
                        AddErrors(usuario.ValidationResult);
                        return View();
                    }

                    FormsAuthentication.SetAuthCookie(vm.Usuario, false);
                    return RedirectToAction("Index", "Dashboard");
                }

                ModelState.AddModelError("", @"É necessário informar suas credenciais");
                return View();
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", @"Erro interno, tente novamente em instantes.");
                return View();
            }
        }

        public ActionResult Logoff()
        {
            FormsAuthentication.SignOut();
            return View("Login");
        }
    }
}

App/AutoFP.Gerencia.MVC.UI/Controllers/DashboardController.cs
using System.Web.Mvc;
using AutoFP.Gerencia.MVC.UI.Controllers.Base;

namespace AutoFP.Gerencia.MVC.UI.Controllers
{
    public class DashboardController : BaseController
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

App/AutoFP.Gerencia.MVC.UI/Controllers/PecaController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoFP.Gerencia.Application.Interface.Produto;
using AutoFP.Gerencia.MVC.UI.Controllers.Base;
using AutoFP.Gerencia.MVC.UI.Factories;
using AutoFP.Gerencia.MVC.UI.ViewModel.Peca;

namespace AutoFP.Gerencia.MVC.UI.Controllers
{
    public class PecaController : BaseController
    {
        private readonly IPecaAppService _pecaAppService;

        public PecaController(IPecaAppService pecaAppService)
        {
            _pecaAppService = pecaAppService;
        }

        public ActionResult Index()
        {
            return View(new List<ListPecaViewModel>() );
        }

        public ActionResult Create()
        {
            var pecaTo = _pecaAppService.FillScreenElements();
            return View(PecaVmFactory.CreateInstanceForSelectList(pecaTo));
        }

        [HttpPost]
        public ActionResult Create(NewPecaViewModel viewModel)
        {
            return View();
        }
    }
}

App/AutoFP.Gerencia.MVC.UI/Controllers/PedidoController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoFP.Gerencia.MVC.UI.Controllers.Base;
using AutoFP.Gerencia.MVC.UI.ViewModel.Pedido;

namespace AutoFP.Gerencia.MVC.UI.Controllers
{
    public class PedidoController : BaseController
    {
        public ActionResult Index()
        {
            return View(new List<ListPedidoViewModel>());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string teste)
        {
            return View();
        }
    }
}

App/AutoFP.Gerencia.MVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AutoFP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    @if (TempData["notification"] != null)
    {
        <div class="alert alert-success" id="notificationData">
            <div class="container">
                @TempData["notification"]
            </div>
        </div>
    }

    <div id="messageNotification" class="alert alert-success hidden">
        <div id="messageNotificationContainer" class="container"></div>
    </div>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AutoFP", "Index", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Categoria peça", "Index", "CategoriaPeca")
                    </li>
                    <li>
                        @Html.ActionLink("Cliente", "Index", "Cliente")
                    </li>
                    <li>
                        @Html.ActionLink("Fornecedor", "Index", "Fornecedor")
                    </li>
                    <li>
                        @Html.ActionLink("Marca", "Index", "Marca")
                    </li>
                    <li>
                        @Html.ActionLink("Montadora", "Index", "Montadora")
                    </li>
                    <li>
                        @Html.ActionLink("Produtos", "Index", "Peca")
                    </li>
                    <li>
                        @Html.ActionLink("Pedidos", "Index", "Pedido")
                    </li>
                    <li>
                        @Html.ActionLink("Sair", "Logoff", "Autenticacao")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Auto FP - Área administrativa</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/notification")
    @RenderSection("scripts", false)
</body>
</html>

App/AutoFP.Gerencia.MVC.UI/Views/Shared/_ModalRemover.cshtml
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labellebdy="deleteModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deleteModalLabel"></h4>
            </div>

            <div class="modal-body">
                <input type="hidden"/>
                <p><span id="messageModal"></span>&nbsp;<label></label>?
                </p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success">Sim, confirmar</button>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/modalRemover")